package com.locusdiary.ui;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import com.locusdiary.closure.ICallback;
import com.locusdiary.module.GeneralComment;
import com.locusdiary.module.GeneralDiary;
import com.locusdiary.module.SessionManager;
import com.locusdiary.module.TimeHelper;
import com.locusdiary.module.User;

public class CommentDialog extends javax.swing.JDialog {
	private ICallback callback;
	private GeneralDiary diary;
    /**
     * Creates new form CommentDialog
     */
	 public CommentDialog(GeneralDiary diary, ICallback callback) {
	        super( );
	        this.callback = callback;
	        this.diary = diary;
	        initComponents();
	    }
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
		setLocationRelativeTo(null);
        jScrollPane1 = new javax.swing.JScrollPane();
        commentTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("添加评论");

        commentTextArea.setColumns(20);
        commentTextArea.setRows(5);
        jScrollPane1.setViewportView(commentTextArea);

        addButton.setText("添加");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    	GeneralComment comment = new GeneralComment();
    	comment.setPublishTime(TimeHelper.getInstance().getCurrentTime());
    	comment.setPublishUser(SessionManager.getInstance().getUser());
    	comment.setContent(commentTextArea.getText());
    	comment.setDiaryId(diary.getId());
    	
    	try {
			assert comment.getContent().length()<50:"评论长度不能大于50！";
		} catch (AssertionError e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null, e.getMessage());
			return;
		}
    	
    	callback.callback(comment);
    	dispose();
    }                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea commentTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
